server:
  port: 8000
    #servlet:
  # context-path: /feign


spring:
  #服务名
  application:
    name: feign




feign:
  hystrix:
    enabled: true


#是否将自己注册到 Eureka-Server 中，默认的为 true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/